import { ScrollText } from 'lucide-react'
import { Panel } from './Panel'
import { ShadowVerdict } from './ShadowVerdict'

export function LogsPanel({ logs, filters, setFilters, sources, dimmed, filtered }) {
  const set = (k) => (e) => setFilters((f) => ({ ...f, [k]: e.target.value }))
  return (
    <Panel icon={ScrollText} title="Live Logs Feed" dimmed={dimmed}
           badge={`${logs.length} shown`} badgeColor="cyan">
      <div className="logs-controls">
        <input className="search-input" placeholder="🔍 Search logs…" value={filters.search} onChange={set('search')} />
        <select className="filter-select" value={filters.severity} onChange={set('severity')}>
          <option value="">All Severities</option>
          <option value="critical">🔴 Critical</option>
          <option value="high">🟠 High</option>
          <option value="medium">🟡 Medium</option>
          <option value="low">🟢 Low</option>
        </select>
        <select className="filter-select" value={filters.source} onChange={set('source')}>
          <option value="">All Sources</option>
          {sources.map(s => <option key={s} value={s}>{s}</option>)}
        </select>
      </div>
      <div className="logs-table-wrap">
        <table className="logs-table">
          <thead>
            <tr>
              <th>Time</th><th>Origin</th><th>Source</th><th>Event</th>
              <th>IP Address</th><th>Reputation</th><th>User</th><th>Severity</th><th>Shadow</th>
            </tr>
          </thead>
          <tbody>
            {logs.length === 0 ? (
              <tr><td colSpan="9" style={{ textAlign: 'center', color: 'var(--text-dim)' }}>
                {/* Three different situations, three different sentences. They
                    used to share one "Waiting for logs…" that also covered a
                    dead backend. */}
                {filtered ? 'No logs match these filters' : 'No logs ingested yet'}
              </td></tr>
            ) : logs.map((log, i) => (
              <tr key={log.id || i} className={
                (log.dropped ? 'log-dropped ' : '') +
                (log.severity === 'critical' ? 'critical-severity' : log.severity === 'high' ? 'high-severity' : '')
              }>
                <td>{log.timestamp ? new Date(log.timestamp).toLocaleTimeString() : '—'}</td>
                <td>
                  <span className={`origin-tag origin-${(log.origin || '').split(':')[0]}`} title={
                    log.origin === 'synthetic' ? 'Generated by this app, and labelled as such'
                      : `Real input via ${log.origin}`
                  }>{log.origin}</span>
                  {/* A suppressed event still appears, marked. Hiding it would
                      make the blocklist invisible in the one view where its
                      effect is observable. */}
                  {log.dropped && <span className="dropped-tag" title="Suppressed by the blocklist before detection ran">dropped</span>}
                </td>
                <td><span className="source-tag">{log.source}</span></td>
                <td>{log.event?.replace(/_/g, ' ')}</td>
                <td className="mono">{log.ip}</td>
                <td><span className={`rep rep-${log.reputation?.verdict || 'unknown'}`}
                        title={log.reputation?.detail}>{log.reputation?.verdict?.replace(/_/g, ' ') || '—'}</span></td>
                <td>{log.user}</td>
                <td><span className={`severity ${log.severity}`}><span className="severity-dot"></span>{log.severity}</span></td>
                <td><ShadowVerdict verdict={log.shadow_verdict} /></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  )
}
